name: Build IPA

on: workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - run: |
          cd ios
          xcodebuild -workspace 'MyProject.xcworkspace' -scheme 'MyProject' -configuration Debug -destination 'generic/platform=iOS Simulator' -derivedDataPath build
