name: Build IPA

on: workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: |
          cd ios
          pod install
      - run: |
          cd ios
          xcodebuild -workspace 'GitProject.xcworkspace' -scheme 'GitProject' -configuration Debug -destination 'generic/platform=iOS Simulator' -derivedDataPath build
