name: Export IPA

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'App version'
        required: false
        default: '1.0.0'
      build_type:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - run: xcodebuild -exportArchive -archivePath "workcenterSD.xcarchive" -exportPath "output"
